name: snap
on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-tags: true

    # Build the snap
    - uses: snapcore/action-build@v1
      with:
        snapcraft-channel: latest/edge
      id: build-snap
      env:
        SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS: 1

    # Make sure the snap is installable
    - run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}

    # Save snap for subsequent job(s)
    - uses: actions/upload-artifact@v3
      with:
        name: husarion-ouster
        path: ${{ steps.build-snap.outputs.snap }}

  publish:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:

    # install dependencies preventing the snap to be set to the store
    - name: Install dependencies
      run: sudo apt-get install -y openjdk-11-jre-headless ca-certificates-java ca-certificates

    # Retrieve the snap
    - uses: actions/download-artifact@v3
      with:
        name: husarion-ouster
        path: .

    # Publish the snap on the store
    # by default on 'edge' but on 'candidate' for tags
    - uses: snapcore/action-publish@v1
      id: publish_snap
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{needs.build.outputs.snap-file}}
        release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}

    # Print the log file if the publish step fails
    - name: Print Snapcraft Log
      if: failure() && steps.publish_snap.outcome == 'failure'
      run: |
        ls -la /home/runner/.local/state/snapcraft/log/
        cat /home/runner/.local/state/snapcraft/log/*.log
